//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

pub use super::app_config::Entity as AppConfig;
pub use super::audio_data::Entity as AudioData;
pub use super::chime_data::Entity as ChimeData;
pub use super::daily_chimes::Entity as DailyChimes;
pub use super::public_holidays::Entity as PublicHolidays;
pub use super::schedule::Entity as Schedule;
